//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUEnrolment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASPNETDBEntities : DbContext
    {
        public ASPNETDBEntities()
            : base("name=ASPNETDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<Prerequisites_Subject> Prerequisites_Subject { get; set; }
        public DbSet<Request> Requests { get; set; }
        public DbSet<Result> Results { get; set; }
        public DbSet<Student_Subject> Student_Subject { get; set; }
        public DbSet<Subject> Subjects { get; set; }
    }
}
