//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUEnrolment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prerequisites_Subject
    {
        public int Id { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> PrerequisiteID { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
