//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUEnrolment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Subject
    {
        public int Id { get; set; }
        public int SubjectID { get; set; }
        public int Completed { get; set; }
        public System.Guid StudentID { get; set; }
        public Nullable<double> Result { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
